"""restore_ip_metadata_v3

Revision ID: ca7875da5a8f
Revises: a3b7c920d1e4
Create Date: 2026-02-25 17:48:38.415801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'ca7875da5a8f'
down_revision: Union[str, Sequence[str], None] = 'a3b7c920d1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_refresh_token'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.alter_column('chat_sessions', 'visitor_fingerprint',
               existing_type=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=12),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'device_type',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'session_status',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('ACTIVE', 'CLOSED', name='session_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("('ACTIVE')"))
    op.alter_column('chat_sessions', 'conversation_mode',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('BOT', 'HUMAN', name='conversation_mode_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("('BOT')"))
    op.alter_column('chat_sessions', 'status',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("('bot')"))
    op.drop_index(op.f('ix_chat_sessions_is_active'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_last_activity'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_id_active'), table_name='chat_sessions')
    op.drop_index(op.f('ix_sessions_lead_lookup'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_assigned_agent_id'), 'chat_sessions', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_conversation_mode'), 'chat_sessions', ['conversation_mode'], unique=False)
    op.create_index(op.f('ix_chat_sessions_is_deleted'), 'chat_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chat_sessions_lead_id'), 'chat_sessions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_status'), 'chat_sessions', ['session_status'], unique=False)
    op.create_index(op.f('ix_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_visitor_fingerprint'), 'chat_sessions', ['visitor_fingerprint'], unique=False)
    op.create_index('ix_sessions_agent', 'chat_sessions', ['assigned_agent_id', 'session_status'], unique=False)
    op.create_index('ix_sessions_tenant_activity_desc', 'chat_sessions', ['tenant_id', 'last_activity_utc'], unique=False)
    op.create_index('ix_sessions_tenant_deleted', 'chat_sessions', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index('ix_sessions_tenant_fingerprint', 'chat_sessions', ['tenant_id', 'visitor_fingerprint'], unique=False)
    op.create_index('ix_sessions_tenant_lead', 'chat_sessions', ['tenant_id', 'lead_id'], unique=False)
    op.create_index('ix_sessions_tenant_status_activity', 'chat_sessions', ['tenant_id', 'session_status', 'last_activity_utc'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'users', ['assigned_agent_id'], ['id'])
    op.drop_column('chat_sessions', 'ip_address')
    op.drop_column('conversations', 'ip_address')
    op.create_foreign_key(None, 'lead_status_history', 'leads', ['lead_id'], ['id'])
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('NEW', 'IN_PROGRESS', 'QUALIFIED', 'CLOSED', 'COMPLETE', name='lead_status'),
               nullable=False)
    op.alter_column('leads', 'updated_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.alter_column('leads', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('leads', 'status',
               existing_type=sa.Enum('NEW', 'IN_PROGRESS', 'QUALIFIED', 'CLOSED', 'COMPLETE', name='lead_status'),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('leads', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_constraint(None, 'lead_status_history', type_='foreignkey')
    op.add_column('conversations', sa.Column('ip_address', sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('chat_sessions', sa.Column('ip_address', sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index('ix_sessions_tenant_status_activity', table_name='chat_sessions')
    op.drop_index('ix_sessions_tenant_lead', table_name='chat_sessions')
    op.drop_index('ix_sessions_tenant_fingerprint', table_name='chat_sessions')
    op.drop_index('ix_sessions_tenant_deleted', table_name='chat_sessions')
    op.drop_index('ix_sessions_tenant_activity_desc', table_name='chat_sessions')
    op.drop_index('ix_sessions_agent', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_visitor_fingerprint'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_tenant_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_status'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_lead_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_is_deleted'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_conversation_mode'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_assigned_agent_id'), table_name='chat_sessions')
    op.create_index(op.f('ix_sessions_lead_lookup'), 'chat_sessions', ['tenant_id', 'lead_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id_active'), 'chat_sessions', ['session_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_chat_sessions_last_activity'), 'chat_sessions', ['last_activity_utc'], unique=False)
    op.create_index(op.f('ix_chat_sessions_is_active'), 'chat_sessions', ['is_active'], unique=False)
    op.alter_column('chat_sessions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('bot')"))
    op.alter_column('chat_sessions', 'conversation_mode',
               existing_type=sa.Enum('BOT', 'HUMAN', name='conversation_mode_enum'),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('BOT')"))
    op.alter_column('chat_sessions', 'session_status',
               existing_type=sa.Enum('ACTIVE', 'CLOSED', name='session_status_enum'),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('ACTIVE')"))
    op.alter_column('chat_sessions', 'device_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'visitor_fingerprint',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.create_table('refresh_sessions',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=512, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__refresh___3213E83F9387EAE4'))
    )
    op.create_index(op.f('ix_refresh_sessions_refresh_token'), 'refresh_sessions', ['refresh_token'], unique=False)
    # ### end Alembic commands ###
